### ISSUE TITLE
Error with AVR128DB48 Curiosity Nano

### ISSUE THREAD

**Issue by leo60228** [stemnic/pyAVRdbg#12]
An exception is thrown immediately after connecting with gdb:
```
ERROR:pyedbglib.protocols.jtagice3protocol:JTAGICE3 error response code 0x35: 'AVR8_FAILURE_INVALID_SIZE: Asked for too many or too few bytes' 
Traceback (most recent call last):
  File "main.py", line 333, in <module>
    handleData(conn, data)
  File "main.py", line 306, in handleData
    handleCommand(socket, packet_data)
  File "main.py", line 178, in handleCommand
    data = dbg.readFlash(int(addr, 16), int(size, 16))
  File "/home/leo60228/pyAVRdbg/debugger.py", line 91, in readFlash
    return self.device.read(self.memoryinfo.memory_info_by_name('flash'), address, numBytes)
  File "/home/leo60228/.local/lib/python3.8/site-packages/pymcuprog/nvmupdi.py", line 274, in read
    data = self.avr.read_memory_section(memtype, offset, numbytes, numbytes)
  File "/home/leo60228/.local/lib/python3.8/site-packages/pymcuprog/avr8target.py", line 96, in read_memory_section
    data.extend(self.protocol.memory_read(memory_type, start_address, read_chunk_size))
  File "/home/leo60228/.local/lib/python3.8/site-packages/pyedbglib/protocols/avr8protocol.py", line 366, in memory_read
    return self.check_response(self.jtagice3_command_response(
  File "/home/leo60228/.local/lib/python3.8/site-packages/pyedbglib/protocols/jtagice3protocol.py", line 210, in check_response
    raise Jtagice3ResponseError(error_message, data[0])
pyedbglib.protocols.jtagice3protocol.Jtagice3ResponseError: AVR8_FAILURE_INVALID_SIZE: Asked for too many or too few bytes
```
Here's the full log: https://gist.github.com/leo60228/69543913c91d9eb603e99352bc9aae19

**Comment by stemnic** [comment]
Thanks for the repport, did you try todo anything specifically or did you just attach to the target over avr-gdb?
It's seems like there is a bug here that we don't read enough bytes from the device causing an exepiton with small reads

**Comment by leo60228** [comment]
This was immediately after attaching, yeah.
